version: "3.7"

services:
  reverseproxy:
    build:
      context: ./compose/docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always

  api:
    depends_on:
      - reverseproxy
    build:
      context: ./webapi
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: always
    environment:
      DefaultConnection: "host=postgres_image;port=5433;database=NetClock;username=snicoper;password=123456"

  postgres_image:
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: "snicoper"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "NetClock"

# docker-compose build
# docker-compose up -d
# docker-compose down

# Browse to: http://localhost/swagger
