version: "3.8"

services:
  reverseproxy:
    build:
      context: ./compose/docker/nginx
      dockerfile: Dockerfile
    ports:
      - "5101:443"
    restart: always

  postgres_image:
    build:
      context: ./compose/docker/postgresql
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=netclock
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=NetClock

  webapi:
    depends_on:
      - reverseproxy
    build:
      context: ./webapi
      dockerfile: Dockerfile
    expose:
      - "5001"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  webapp:
    depends_on:
      - reverseproxy
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "4210:4200"
    restart: always

volumes:
  db_volume:

# docker-compose build
# docker-compose up -d
# docker-compose down

# Browse to: http://localhost:4210
