image: microsoft/dotnet:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script:
        - "cd tests/WebApi.IntegrationTests"
        - "dotnet test /p:CollectCoverage=true"
    coverage: '/^\|\s*Total\s*\|[^|]*\|\s*(\d+\.\d+)/'
